pipeline {
    agent any
       stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'jnekins_ci',
                    url: 'https://github.com/pabhishek1994-pixel/simple-java-maven-app.git'
            }
        }
        stage("Maven build") {
            steps {
                sh '''
                    mvn clean package
                '''
            }
        }
        stage('Sonar') {
            steps {
                withCredentials([string(credentialsId: 'sonar_server', variable: 'SONAR_TOKEN')]) {
                    sh '''
                        sonar-scanner \
                        -Dsonar.projectKey=java \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://3.108.54.7:9000 \
                        -Dsonar.token=$SONAR_TOKEN
                    '''
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}