pipeline {
    agent any

    environment {
        SONAR_HOST_URL = 'http://13.235.86.100:9000'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'jnekins_ci',
                    url: 'https://github.com/pabhishek1994-pixel/simple-java-maven-app.git'
            }
        }
        stage("Maven build") {
            steps {
                sh '''
                    mvn clean package
                '''
            }
        }
        stage('Sonar') {
            steps {
                withCredentials([string(credentialsId: 'sonar-server', variable: 'SONAR_TOKEN')]) {

                    sh '''
                        mvn clean verify sonar:sonar \            
                        -Dsonar.host.url=$SONAR_HOST_URL \
                        -Dsonar.token=$SONAR_TOKEN
                    '''
                }
            }
        }
    }
}